{ config, lib, pkgs, ... }: {
  imports = [
    ./tint2.nix
    ./aio.nix
    ./rofi
    ./gtk.nix
    ./zsh.nix
    ./neovim.nix
    ./polybar.nix
    ./nerdfonts.nix
    ./x11eventcallbacks.nix
    ./kitty.nix
    ./sxhkd.nix
    ./bspwm.nix
    ./btop.nix
    ./picom.nix
    ./wezterm.nix
    ./ranger.nix
    ./dunst.nix
    ./betterlockscreen.nix
    ./fusuma.nix
    ./xbindkeys.nix
    ./spicetify.nix
    ./guake.nix
    ./obsmic.nix
    ./waybar.nix
    ./wofi.nix
    ./hyprland.nix
    ./thunderbird.nix
    ./helix.nix
    ./pentest.nix
  ];
}
