{ ... }: {
  imports = [
    ./settings.nix
    ./stylix
    ./git.nix

    ./lazygit.nix
    ./openrgb.nix
    ./mangohud.nix
    ./zsh.nix
    ./firefox.nix
    ./alacritty.nix
    ./kitty.nix
    ./sxhkd.nix
    ./nerdfonts.nix
    ./neovim.nix
    ./bspwm.nix
    ./gtk.nix
    ./btop.nix
    ./wofi
    ./dunst.nix
    ./guake.nix
    ./helix.nix
    ./picom.nix
    ./tint2.nix
    ./fusuma.nix
    ./ranger.nix
    ./waybar.nix
    ./pentest.nix
    ./polybar.nix
    ./wezterm.nix
    ./xbindkeys.nix
    ./thunderbird.nix
    ./betterlockscreen.nix
    ./tmux.nix
    ./flameshot.nix
    ./bat.nix
    ./nitrogen.nix
    ./autolock.nix
    ./polkit.nix
    ./gammastep.nix

    ./hyprland.nix
    ./hyprlock.nix
    ./hyprpaper.nix
    ./hypridle.nix
    ./swaylock.nix
    ./swayidle.nix
    ./wlogout

    ./mechvibes
    ./x11eventcallbacks
    ./rofi
    ./spotify
    ./obsmic
    ./direnv.nix
    ./poetry.nix
    ./bitwarden.nix
    ./catppuccin
    ./ssh.nix
    ./zathura.nix
    ./easyeffects.nix

    ./i3.nix
    ./qt.nix
    ./flatpak.nix
    ./yazi
    ./eog.nix
    ./zoxide.nix
    ./nh.nix
  ];
}
