#! /bin/sh

nitrogen --restore &
pgrep -x picom > /dev/null || picom -f &
pgrep -x sxhkd > /dev/null || sxhkd &
/home/dreadster/.config/polybar/shades/launch.sh &
xsetroot -cursor_name left_ptr 
xrandr --output DP-0 --primary --output HDMI-0 --left-of DP-0 --rotate left
vmware-user &

bspc monitor DP-0 -d 1 3 5 7 9
bspc monitor HDMI-0 -d 2 4 6 8 10

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
